a_records_old = {
    '01-15-2024': ['Michael, Salem', 'Gavrilov, Daniil', 'Umana, Byron', 'Walker, Wisdom', 'Michael, Salem'],
    '01-16-2024': ['Kubicek, Lee', 'Niroula, Aayush', 'Hernandez Trejo, Jesus', 'Kubicek, Lee',
                   'Michael, Salem', 'Niroula, Aayush', 'Hernandez Trejo, Jesus', 'Kubicek, Lee',
                   'Niroula, Aayush', 'Patel, Raghav'],
    '01-17-2024': ['Harris, Jakada', 'Basnet, Sushmita', 'Harris, Jakada', 'Patel, Raghav', 'Basnet, Sushmita',
                   'Harris, Jakada'],
    '01-18-2024': ['Basnet, Sushmita', 'Owens, Aeneas', 'Smith, Kayla Liyah', 'Weinstein, Jacob',
                   'Walker, Wisdom', 'Weinstein, Jacob'], '01-19-2024': ['Shmonov, Bogdan'],
    '01-20-2024': ['Gavrilov, Daniil', 'Joshi, Rajarshi', 'Shmonov, Bogdan'],
    '01-21-2024': ['Lux, Christian', 'Molina, Jahir', 'Lux, Christian', 'Molina, Jahir', 'Gavrilov, Daniil',
                   'Lux, Christian'],
    '01-22-2024': ['Hernandez Trejo, Jesus', 'Mejia, Humberto', 'Avila, Lesley', 'Hernandez, Kimberly',
                   'Mejia, Humberto', 'Tenny, Britt', 'Avila, Lesley', 'Hernandez, Kimberly',
                   'Joshi, Rajarshi', 'Mejia, Humberto', 'Molina, Jahir', 'Ndongla, Rudy', 'Owens, Aeneas',
                   'Smith, Kayla Liyah', 'Tenny, Britt', 'Umana, Byron', 'Hernandez Trejo, Jesus',
                   'Niroula, Aayush', 'Shmonov, Bogdan', 'Walker, Wisdom', 'Niroula, Aayush',
                   'Niroula, Aayush', 'Shmonov, Bogdan'],
    '01-23-2024': ['Basnet, Sushmita', 'Patel, Raghav', 'Basnet, Sushmita'],
    '01-24-2024': ['Michael, Salem', 'Smith, Kayla Liyah', 'Smith, Kayla Liyah', 'Hernandez Trejo, Jesus',
                   'Michael, Salem', 'Smith, Kayla Liyah', 'Walker, Wisdom']}

a_records = {'01-15-2024': ['Reames, Ethan'],
             '01-17-2024': ['Melnychuk, Yuriy'],
             '01-18-2024': ['Rokayah, Nfn'],
             '01-20-2024': ['Hanson, Jennifer', 'Ume, Amadi', 'Wright, Barry'],
             '01-21-2024': ['Burgess, Jason', 'Fullerton, Garrett', 'McDaniel, Monica', 'Verduzco Sanchez, Sergio'],
             '01-22-2024': ['Borishkevich, Mark', 'Boyd, Howard', 'Caudill, Devon', 'Cayemitte, Carl',
                            'Kioroglo, Natalie', 'Nguyen, Han', 'Phifer, Jeremiah', 'Shen, Guobin', 'Burgess, Jason',
                            'Kioroglo, Natalie', 'Melnychuk, Yuriy', 'Nguyen, Han', 'Ume, Amadi']}
