[theme]
base = "light"
#primaryColor = "#B6A269"  # CENTRAL PIEDMONT GRAY
primaryColor = "#636466"  # CENTRAL PIEDMONT GOLD
secondaryBackgroundColor = "#B6A269"  # CENTRAL PIEDMONT GRAY
backgroundColor = "#ffffff"  # White background
textColor = "#007396"  # PANTONE 633 C - Blue
font="Franklin Gothic"
