[theme]
base = "light"
primaryColor = "#007396"
secondaryBackgroundColor = "#636466"
backgroundColor = "#ffffff"  # White background
textColor = "#B6A269"
font="Franklin Gothic"


# "#B6A269"  # CENTRAL PIEDMONT GRAY
# "#636466"  # CENTRAL PIEDMONT GOLD
# "#007396"  # CENTRAL PIEDMONT Blue
